AppName = Smith Micro Image Assistant
BackgroundColor = FAFAFA
BaseDir = C:\AHK
BatchDir = C:\AHK\batch
ConfigFileLoc = C:\AHK\config.db
CountDownSec = 5
DownloadDir = C:\AHK\downloads
LogLoc = C:\AHK\progress.log
ThemeDir = C:\AHK\theme